In [1]:
import tensorflow as tf
import random
import numpy as np
from utils import num_to_char, char_to_num
from data_pipeline import test, data
from model import load_model

In [2]:
sample = test.as_numpy_iterator().next()

In [3]:
model = load_model()
model.load_weights('models/checkpoint')

In [4]:
yhat = model.predict(sample[0])

1/1 [==============================] - 3s 3s/step


In [5]:
print('~'*20, 'REAL TEXT','~'*20)
[tf.strings.reduce_join([num_to_char(word) for word in sentence]) for sentence in sample[1]]

~~~~~~~~~~~~~~~~~~~~ REAL TEXT ~~~~~~~~~~~~~~~~~~~~


[<tf.Tensor: shape=(), dtype=string, numpy=b'bin blue at f three soon'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'lay red by e seven soon'>]

In [6]:
decoded = tf.keras.backend.ctc_decode(yhat, input_length=[75,75], greedy=True)[0][0].numpy()
print('~'*20, 'PREDICTIONS','~'*20)
[tf.strings.reduce_join([num_to_char(word) for word in sentence]) for sentence in decoded]


~~~~~~~~~~~~~~~~~~~~ PREDICTIONS ~~~~~~~~~~~~~~~~~~~~


[<tf.Tensor: shape=(), dtype=string, numpy=b'se ree it n nive agin'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b's ree in s sive again'>]